export type QuoteCategory = "motivational" | "comfort" | "burnout" | "stoicism";

export type Quote = {
  id: number;
  text: string;
  author: string;
  category: QuoteCategory;
  source: string;
  videoUrl: string;
};

export const QUOTES: Quote[] = [
  
  {
    id: 1,
    text: "늘 갈망하고, 늘 겸손하세요. (Stay hungry, stay foolish.)",
    author: "스티브 잡스 (Steve Jobs)",
    category: "motivational",
    source: "Stanford 졸업식 연설 (2005)",
    videoUrl: "https://www.youtube.com/watch?v=UF8uR6Z6KLc",
  },
  {
    id: 2,
    text: "세상을 바꾸고 싶다면, 매일 아침 침대 정리부터 시작하세요.",
    author: "윌리엄 맥레이븐 (William H. McRaven)",
    category: "motivational",
    source: "University of Texas at Austin 졸업식 연설 (2014)",
    videoUrl: "https://www.youtube.com/watch?v=pxBQLFLei70",
  },
  {
    id: 3,
    text: "실패는 우리 삶에서 불필요한 것들을 걷어냅니다. 저는 바닥에서 다시 시작해야 했습니다.",
    author: "J.K. 롤링 (J.K. Rowling)",
    category: "comfort", 
    source: "Harvard 졸업식 연설 (2008)",
    videoUrl: "https://www.youtube.com/watch?v=wHGqp8lz36c",
  },
  {
    id: 4,
    text: "넘어지는 건 피할 수 없지만, 거기 계속 누워 있을지는 우리의 선택입니다.",
    author: "오프라 윈프리 (Oprah Winfrey)",
    category: "motivational",
    source: "Harvard 졸업식 연설 (2013)",
    videoUrl: "https://www.youtube.com/watch?v=GMWFieBGR7c",
  },
  {
    id: 5,
    text: "꿈을 향해 달리다 넘어지더라도, 앞으로 넘어지세요. (Fall forward.)",
    author: "덴젤 워싱턴 (Denzel Washington)",
    category: "motivational",
    source: "UPenn 졸업식 연설 (2011)",
    videoUrl: "https://www.youtube.com/watch?v=tbnzAVRZ9Xc",
  },
  {
    id: 6,
    text: "두려움이 당신 인생의 방향을 정하도록 내버려 두지 마세요.",
    author: "짐 캐리 (Jim Carrey)",
    category: "motivational",
    source: "Maharishi University 졸업식 연설 (2014)",
    videoUrl: "https://www.youtube.com/watch?v=V80-gPkpH6M",
  },
  {
    id: 7,
    text: "가장 중요한 것은 무엇을 이루었느냐가 아니라, 어떤 방식으로 살아왔느냐입니다.",
    author: "엘런 드제너러스 (Ellen DeGeneres)",
    category: "comfort",
    source: "Tulane University 졸업식 연설 (2009)",
    videoUrl: "https://www.youtube.com/watch?v=0e8ToRVOtRo",
  },
  {
    id: 8,
    text: "삶은 계획한 대로 흘러가지 않습니다. 그리고 그게 오히려 더 멋질 때가 많습니다.",
    author: "코난 오브라이언 (Conan O'Brien)",
    category: "comfort",
    source: "Dartmouth 졸업식 연설 (2011)",
    videoUrl: "https://youtu.be/ELC_e2QBQMk?si=Wf6iSno4Cz2h7UJ7",
  },
  {
    id: 9,
    text: "우리는 스스로 생각하는 것보다 훨씬 더 강한 존재입니다.",
    author: "아놀드 슈워제네거 (Arnold Schwarzenegger)",
    category: "motivational",
    source: "6 Rules of Success 연설",
    videoUrl: "https://www.youtube.com/watch?v=EyhOmBPtGNM",
  },
  {
    id: 10,
    text: "제 영웅은요? 10년 뒤의 저 자신입니다.",
    author: "매튜 맥커너히 (Matthew McConaughey)",
    category: "motivational",
    source: "Oscars 86th 수상 소감",
    videoUrl: "https://youtube.com/shorts/47BoYCFGrJ0?si=1Hc9xJnxPYHxfR5z",
  },

  // 2. TED Talks (Insight & Growth)
  {
    id: 11,
    text: "취약함은 약함이 아닙니다. 오히려 용기를 가장 정확하게 보여 주는 척도입니다.",
    author: "브레네 브라운 (Brené Brown)",
    category: "comfort",
    source: "TED: The power of vulnerability",
    videoUrl: "https://www.youtube.com/watch?v=iCvmsMzlF7o",
  },
  {
    id: 12,
    text: "사람들은 당신이 무엇을 하는지가 아니라, 왜 하는지를 보고 선택합니다.",
    author: "사이먼 시넥 (Simon Sinek)",
    category: "motivational", 
    source: "TED: How great leaders inspire action",
    videoUrl: "https://www.youtube.com/watch?v=qp0HIF3SfI4",
  },
  {
    id: 13,
    text: "재능보다 더 중요한 건 끝까지 해내는 힘, 바로 그릿(grit)입니다.",
    author: "앤절라 더크워스 (Angela Duckworth)",
    category: "motivational",
    source: "TED: Grit: The power of passion and perseverance",
    videoUrl: "https://www.youtube.com/watch?v=H14bBuluwB8",
  },
  {
    id: 14,
    text: "무언가 하고 싶다면 5초 안에 움직이세요. 5, 4, 3, 2, 1.",
    author: "멜 로빈스 (Mel Robbins)",
    category: "motivational",
    source: "TEDx: How to stop screwing yourself over",
    videoUrl: "https://www.youtube.com/watch?v=Lp7E973zozc",
  },
  {
    id: 15,
    text: "자세가 바뀌면 마음도 달라집니다. 단 2분만 투자해 보세요.",
    author: "에이미 커디 (Amy Cuddy)",
    category: "comfort",
    source: "TED: Your body language may shape who you are",
    videoUrl: "https://www.youtube.com/watch?v=Ks-_Mh1QhMc",
  },
  {
    id: 16,
    text: "창의성은 실수할 각오가 된 사람에게 찾아옵니다.",
    author: "켄 로빈슨 (Sir Ken Robinson)",
    category: "motivational", 
    source: "TED: Do schools kill creativity?",
    videoUrl: "https://www.youtube.com/watch?v=iG9CE55wbtY",
  },
  {
    id: 17,
    text: "스트레스를 적이 아니라 동반자로 보면, 스트레스는 당신을 더 강하게 만듭니다.",
    author: "켈리 맥고니걸 (Kelly McGonigal)",
    category: "burnout",
    source: "TED: How to make stress your friend",
    videoUrl: "https://www.youtube.com/watch?v=RcGyVTAoXEU",
  },
  {
    id: 18,
    text: "행복해서 성공하는 것이지, 성공했다고 행복해지는 게 아닙니다.",
    author: "숀 에이커 (Shawn Achor)",
    category: "comfort",
    source: "TED: The happy secret to better work",
    videoUrl: "https://www.youtube.com/watch?v=fLJsdqxnZb0",
  },
  {
    id: 19,
    text: "단 하나의 이야기만 듣는 것은 위험합니다. 서로 다른 이야기를 들을 때 진짜 세상이 보입니다.",
    author: "치마만다 응고지 아디치에 (Chimamanda Ngozi Adichie)",
    category: "stoicism", 
    source: "TED: The danger of a single story",
    videoUrl: "https://www.youtube.com/watch?v=D9Ihs241zeg",
  },
  {
    id: 20,
    text: "미루는 습관은 우리 안에 사는 원숭이 때문이다. 특히 마감일이 없을 때 가장 위험하다.",
    author: "팀 어번 (Tim Urban)",
    category: "motivational",
    source: "TED: Inside the mind of a master procrastinator",
    videoUrl: "https://www.youtube.com/watch?v=arj7oStGLkU",
  },
  {
    id: 21,
    text: "“할 수 있다”는 믿음, 그 생각 자체가 당신의 능력을 결정합니다.",
    author: "스콧 겔러 (Scott Geller)",
    category: "motivational",
    source: "TEDx: The psychology of self-motivation",
    videoUrl: "https://www.youtube.com/watch?v=7sxpKhIbr0E",
  },
  {
    id: 22,
    text: "내향적인 성격은 고쳐야 할 결함이 아니라, 세상을 바꾸는 조용한 힘입니다.",
    author: "수전 케인 (Susan Cain)",
    category: "comfort",
    source: "TED: The power of introverts",
    videoUrl: "https://www.youtube.com/watch?v=c0KYU2j0TM4",
  },
  {
    id: 23,
    text: "좋은 삶은 부나 명예에서 오지 않습니다. 결국 사람과의 좋은 관계에서 옵니다.",
    author: "로버트 월딩어 (Robert Waldinger)",
    category: "comfort",
    source: "TED: What makes a good life?",
    videoUrl: "https://www.youtube.com/watch?v=8KkKuTCFvzI",
  },
  {
    id: 24,
    text: "영감은 기다리는 사람이 아니라, 매일 작업실에 나가는 사람에게 옵니다.",
    author: "엘리자베스 길버트 (Elizabeth Gilbert)",
    category: "motivational",
    source: "TED: Your elusive creative genius",
    videoUrl: "https://www.youtube.com/watch?v=86x-u-tz0MA",
  },
  {
    id: 25,
    text: "행복한 삶을 위한 나의 철학: 바꿀 수 없는 것에 매달리지 마세요.",
    author: "샘 번스 (Sam Berns)",
    category: "comfort",
    source: "TEDx: My philosophy for a happy life",
    videoUrl: "https://www.youtube.com/watch?v=36m1o-tM05g",
  },

  // 3. Movie Speeches & Famous Scenes
  {
    id: 26,
    text: "누구도, 그 누구도 네게 “넌 못 해”라고 말하게 두지 마. 아빠인 나라도 마찬가지야.",
    author: "크리스 가드너 (윌 스미스)",
    category: "motivational",
    source: "The Pursuit of Happyness (영화)",
    videoUrl: "https://youtu.be/n4fcaC2k0jc?si=v5dPonO8lmETq7Yg",
  },
  {
    id: 27,
    text: "인생이 널 얼마나 세게 때리느냐는 중요하지 않아. 맞고도 계속 나아갈 수 있느냐가 중요하지.",
    author: "록키 발보아 (Sylvester Stallone)",
    category: "motivational",
    source: "Rocky Balboa (영화)",
    videoUrl: "https://youtu.be/D_Vg4uyYwEk?si=Qeo-3JwgYGMrORAz",
  },
  {
    id: 28,
    text: "카르페 디엠, 지금 이 순간을 붙잡아라. 너만의 인생을 특별하게 만들어라.",
    author: "존 키팅 (Robin Williams)",
    category: "motivational",
    source: "Dead Poets Society (영화)",
    videoUrl: "https://www.youtube.com/watch?v=vi0Lbjs5ECI",
  },
  {
    id: 29,
    text: "우리가 진짜로 두려워해야 할 것은 우리가 부족하다는 게 아니라, 상상 이상으로 강력하다는 사실입니다.",
    author: "티모 크루즈 (Rick Gonzalez)",
    category: "motivational",
    source: "Coach Carter (영화)",
    videoUrl: "https://www.youtube.com/watch?v=2_fDhqRk_Ro",
  },
  {
    id: 30,
    text: "1인치, 그 작은 1인치를 위해 우리는 싸운다. 인생이란 결국 그 1인치들의 싸움이다.",
    author: "토니 디아마토 (Al Pacino)",
    category: "motivational",
    source: "Any Given Sunday (영화)",
    videoUrl: "https://www.youtube.com/watch?v=WO4tIrjBDkk",
  },
  {
    id: 31,
    text: "완벽함이란 점수판의 승리가 아니라, 서로의 눈을 보고 “우린 서로를 실망시키지 않았다”고 말할 수 있는 것이다.",
    author: "코치 게인즈 (Billy Bob Thornton)",
    category: "comfort",
    source: "Friday Night Lights (영화)",
    videoUrl: "https://www.youtube.com/watch?v=o-iPiN_YHjY",
  },
  {
    id: 32,
    text: "우리가 왜 넘어지는 줄 아니? 다시 일어서는 법을 배우기 위해서야.",
    author: "토머스 웨인",
    category: "motivational",
    source: "Batman Begins (영화)",
    videoUrl: "https://youtube.com/shorts/6pkZ-w1alkE?si=qisxUpeQrqhpcMuF",
  },
  {
    id: 33,
    text: "희망은 좋은 거야. 어쩌면 가장 좋은 것일지도 몰라. 좋은 것들은 절대 사라지지 않아.",
    author: "앤디 듀프레인",
    category: "comfort",
    source: "The Shawshank Redemption (영화)",
    videoUrl: "https://youtu.be/9K30e9O3Nng?si=FTcX5RT_f5WG4l0E",
  },
  {
    id: 34,
    text: "과거는 아플 수 있어. 하지만 내 생각엔, 피할 수도 있고 거기서 배울 수도 있지.",
    author: "라피키",
    category: "comfort",
    source: "The Lion King (영화)",
    videoUrl: "https://www.youtube.com/watch?v=dZfGTL2PY3E",
  },
  {
    id: 35,
    text: "네 잘못이 아니야. (It’s not your fault.)",
    author: "션 맥과이어 (Robin Williams)",
    category: "comfort",
    source: "Good Will Hunting (영화)",
    videoUrl: "https://youtube.com/shorts/NV79Oe1GNPA?si=LpKSuQec3AbISW9u",
  },

  // 4. Wisdom & Philosophy
  
  {
    id: 37,
    text: "나에겐 꿈이 있습니다. (I have a dream.)",
    author: "마틴 루터 킹 주니어 (Martin Luther King Jr.)",
    category: "motivational",
    source: "워싱턴 행진 연설 (1963)",
    videoUrl: "https://www.youtube.com/watch?v=vP4iY1TtS3s",
  },
  {
    id: 38,
    text: "우리가 진짜 멈추는 가장 좋은 방법은, 그냥 멈추어 서 보는 것입니다.",
    author: "틱낫한 (Thich Nhat Hanh)",
    category: "stoicism",
    source: "Oprah Winfrey 인터뷰",
    videoUrl: "https://youtu.be/5Q5P7GO1Fwk?si=6HatAgCfSUZtsQZH",
  },
  {
    id: 39,
    text: "어린 시절의 꿈을 진짜로 이루는 방법에 대한 마지막 강의.",
    author: "랜디 포시 (Randy Pausch)",
    category: "motivational",
    source: "CMU Last Lecture",
    videoUrl: "https://www.youtube.com/watch?v=ji5_MqicxSo",
  },
  {
    id: 40,
    text: "현재 존재함을 느끼세요. (The power of now.)",
    author: "에크하르트 톨레 (Eckhart Tolle)",
    category: "stoicism",
    source: "Talks at Google",
    videoUrl: "https://youtube.com/shorts/lBZ10SV3X6A?si=WCxEbzwcgbf7GlN-",
  },
  {
    id: 41,
    text: "친절하세요. 언제나, 누구에게나 친절하세요.",
    author: "프레드 로저스 (Mr. Rogers)",
    category: "comfort",
    source: "상원 청문회 연설",
    videoUrl: "https://www.youtube.com/watch?v=fKy7ljRr0AA",
  },
  {
    id: 42,
    text: "“이것 또한 물입니다.” — 어떻게 생각할지를 스스로 선택하는 법에 대하여.",
    author: "데이비드 포스터 월리스 (David Foster Wallace)",
    category: "stoicism",
    source: "Kenyon College 졸업식 연설 (2005)",
    videoUrl: "https://www.youtube.com/watch?v=8CrOL-ydFMI",
  },
  {
    id: 43,
    text: "가장 중요한 건 꺾이지 않는 마음, 바로 맘바 멘탈리티입니다.",
    author: "코비 브라이언트 (Kobe Bryant)",
    category: "motivational",
    source: "Mamba Mentality 인터뷰",
    videoUrl: "https://youtu.be/xd-9D3GzUpo?si=OfEvt7ISWQTD6D52",
  },
  {
    id: 44,
    text: "아무것도 하지 않으면 의심과 두려움이 자라납니다. 행동하면 자신감과 용기가 생겨납니다.",
    author: "데일 카네기 (Dale Carnegie)",
    category: "burnout",
    source: "Motivational Video 모음",
    videoUrl: "https://www.youtube.com/watch?v=fLeJJPxua3E",
  },
  {
    id: 45,
    text: "언제 사람이 변한다고 생각하십니까? ",
    author: "존 맥스웰 (John Maxwell)",
    category: "motivational",
    source: "Leadership 강연",
    videoUrl: "https://youtube.com/shorts/zmy8jt9RcXk?si=KkIUftT1oey5bOR6",
  },
];
